
services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: loan_user
      POSTGRES_PASSWORD: loan_pass123
      POSTGRES_DB: loan_system_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: loan_user
      DATABASE_PASSWORD: loan_pass123
      DATABASE_NAME: loan_system_db
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
    external: false
    name: loan-system-postgres-data
