name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: rg-loan-system-production
  ACR_NAME: loansystemacr
  CONTAINER_APP_NAME: loan-system-app-production

jobs:
  validate:
    name: Validate before Deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: |
          npx nx test backend --coverage
          npx nx test frontend --coverage
      
      - name: Build validation
        env:
          NODE_ENV: production
        run: |
          npx nx build backend --configuration=production
          npx nx build frontend --configuration=production
  
  deploy:
    needs: validate
    name: Deploy to Azure Production
    runs-on: ubuntu-latest
    environment:
      name: production
    
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}

      - name: Build and push to ACR
        run: |
          az acr build \
            --registry ${{ env.ACR_NAME }} \
            --image loan-system:${{ github.sha }} \
            --image loan-system:production-latest \
            --file infrastructure/docker/Dockerfile.prod \
            .

      - name: Deploy to Container Apps
        run: |
          # Para produção, usar Multiple revisions para rollback fácil
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --revision-mode multiple
          
          # Deploy com nova revisão
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/loan-system:production-latest \
            --revision-suffix ${{ github.run_number }}
          
          echo "✅ Production deploy completed"